// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqtMABHXO2GdfR7AIhFzKpxR8X5OolIS0',
    appId: '1:550180066862:android:78e8d2a61499c0f4e631bf',
    messagingSenderId: '550180066862',
    projectId: 'fir-flutter-dev-10b63',
    databaseURL: 'https://fir-flutter-dev-10b63-default-rtdb.firebaseio.com',
    storageBucket: 'fir-flutter-dev-10b63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIARvPFwSCT9EHTO7XETZOAh4bto2NRjw',
    appId: '1:550180066862:ios:b615583e89b402cee631bf',
    messagingSenderId: '550180066862',
    projectId: 'fir-flutter-dev-10b63',
    databaseURL: 'https://fir-flutter-dev-10b63-default-rtdb.firebaseio.com',
    storageBucket: 'fir-flutter-dev-10b63.appspot.com',
    iosClientId: '550180066862-3tvg48kolq77rt4t4tu8esfbbo913a2b.apps.googleusercontent.com',
    iosBundleId: 'com.example.bitcoinApp',
  );
}
